site_name: FitLife Documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - md_in_html
plugins:
  - search
  - render_swagger
  - drawio:
      edit: false
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
