name: PlantUML Diagrams

on:
  pull_request:
    branches:
      - main

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Generate SVG Diagrams
        uses: Timmy/plantuml-action@v1
        with:
          args: -v diagrams/context/*.puml diagrams/container/*.puml diagrams/component/*.puml diagrams/code/*/*.puml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feature(diagrams): update diagrams images"
